# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - erp-sacristia-prod-web

on:
  push:
    branches:
      - DevCanoBaq
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      
      - name: npm install, build, and test
        run: |
          npm install --prefix /home/runner/work/ERP-front-end-/ERP-front-end-/ceo.web
          npm --if-present --prefix /home/runner/work/ERP-front-end-/ERP-front-end-/ceo.web run build
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: /home/runner/work/ERP-front-end-/ERP-front-end-/ceo.web/build/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'erp-sacristia-prod-web'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9FE5DAFA5EB545A9A3F571B4D89B23E3 }}
          package: .
